BaconBookstore/Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaconBookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BaconBookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket cart;
        public CartSummaryViewComponent(Basket cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

BaconBookstore/Components/TypesViewComponent.cs
using BaconBookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaconBookstore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }
        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

BaconBookstore/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-2 p-1 shadow-lg">
    <div class="bg-light p-1 card-header bg-dark">
        <h4 class="text-light">
            @Model.Title
            <span class="badge bg-info" style="float:right">
                <small>$@Model.Price</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">@Model.Category @Model.Classification</div>
    <div class="card-text p-1">Author: @Model.Author</div>
    <div class="card-text p-1">Publisher: @Model.Publisher</div>
    <div class="card-text p-1">ISBN: @Model.Isbn</div>
    <div class="card-text p-1">Page Count: @Model.PageCount</div>

    <form method="post" asp-page="/Cart">
        <input type="hidden" asp-for="@Model.BookId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add</button>
        </span>
    </form>
</div>

BaconBookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="/lib/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Bacon BookStore</div>
                <div class="col-6 float-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>