BaconBookstore/Controllers/PurchaseController.cs
using BaconBookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaconBookstore.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }
        public PurchaseController (IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout (Purchase purchase)
        {
            if (basket.Items.Count() == 0 )
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.LineItems = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseConfirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

BaconBookstore/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaconBookstore.Infrastructure;
using BaconBookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BaconBookstore.Pages
{
    public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        
        public CartModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        // For post methods, use onpost
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);
       
            basket.AddItem(b, 1);

            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove (int bookId, string ReturnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage( new { ReturnUrl = ReturnUrl });
        }
    }
}

BaconBookstore/Pages/PurchaseConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BaconBookstore.Pages
{
    public class PurchaseConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BaconBookstore/Pages/Cart.cshtml
@page
@model BaconBookstore.Pages.CartModel
@{
    bool isEmpty = !Model.basket.Items.Any();
}
<h2>Cart</h2>

<div class="jumbotron jumbotron-fluid @(isEmpty ? "bg-warning" : "bg-info")">
    <div class="container">

        @if (isEmpty)
        {
            <h1 class="display-4">Empty</h1>
            <p class="lead">There are no books in your cart.</p>
        }
        else
        {
            <h1 class="display-4">@Model.basket.Items.Last().Book.Title</h1>
            <p class="lead">You successfully added @Model.basket.Items.Last().Book.Title to your cart!</p>
        }
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Price.ToString("c")</td>
                <td>@((i.Quantity * i.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div class="d-grid gap-2">
    <a class="btn btn-primary" href="@Model.ReturnUrl" data-toggle="tooltip" data-placement="top" title="Back to where you left off!">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Purchase" asp-action="Checkout">Checkout</a>
</div>

BaconBookstore/Pages/PurchaseConfirmation.cshtml
@page
@model BaconBookstore.Pages.PurchaseConfirmationModel
@{
}

<div class="jumbotron jumbotron-fluid bg-success">
    <div class="container">

        <h1 class="display-4">Purchase Confirmation</h1>
        <p class="lead">Your order has been successfully placed.</p>
        <a class="btn btn-primary" asp-controller="Home">Return Home</a>
    </div>
</div>

BaconBookstore/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Bacon BookStore</span>
    </div>

    <div row m-1 p-1>
        @RenderBody()
    </div>
</body>
</html>